# Generated by Django 4.1.2 on 2022-10-30 17:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_make_about_field_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a294678e-dc70-4e1d-84d9-57a4d2dc73b1'), primary_key=True, serialize=False),
        ),
    ]
