# Generated by Django 4.1.2 on 2022-10-31 04:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_create_applicant_resume_score_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7a767d0a-cebd-40c2-87b8-71cfece4c7e9'), primary_key=True, serialize=False),
        ),
    ]
