# Generated by Django 4.1.2 on 2022-10-31 08:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant_match_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b91cbcf1-5dc6-4415-bfce-9f19033af83c'), primary_key=True, serialize=False),
        ),
    ]
