# Generated by Django 4.1.2 on 2022-10-30 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e73106e0-fba9-4526-b482-29dd6119fb90'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('established_date', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=150)),
                ('logo', models.FileField(null=True, upload_to='logos/')),
                ('corporation_type', models.CharField(max_length=150)),
                ('company_size', models.IntegerField()),
                ('website', models.URLField(default='https://example.com/')),
                ('reddit', models.URLField(default='https://reddit.com/r/')),
                ('twitter', models.URLField(default='https://twitter.com/')),
                ('facebook', models.URLField(default='https://facebook.com/')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'companies',
                'verbose_name_plural': 'companies',
                'ordering': ('-created_at',),
            },
        ),
    ]
