# Generated by Django 4.1.2 on 2022-10-30 11:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_create_job_and_application_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b0643ab1-4ca0-4690-993b-d5e0f0227fb5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
