# Generated by Django 4.1.2 on 2022-10-30 17:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_make_about_field_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.UUID('78703115-bfca-47c5-b43c-f04de82c65d8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
