# Generated by Django 4.1.2 on 2022-10-31 04:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_create_applicant_resume_score_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.UUID('924255c7-088a-44bc-bb70-302d0e82128c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
