# Generated by Django 4.1.2 on 2022-10-31 08:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3482dabf-9c8e-4beb-9598-9dd53c157e4c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
