# Generated by Django 4.1.2 on 2022-10-31 09:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_add_match_field_to_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a4ee156c-5977-4c31-b8a5-6e22550b26d5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
