# Generated by Django 4.1.2 on 2022-10-30 11:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_create_job_and_application_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.UUIDField(default=uuid.UUID('06a4ec76-a6b8-42c6-b220-1862d539ab3d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
