# Generated by Django 4.1.2 on 2022-10-30 17:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_make_about_field_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5f829a2f-6711-422e-bcf8-900d64d9ea33'), editable=False, primary_key=True, serialize=False),
        ),
    ]
