# Generated by Django 4.1.2 on 2022-10-31 04:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_create_applicant_resume_score_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7e487468-79e7-4926-831f-2af14b4271bc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
