# Generated by Django 4.1.2 on 2022-10-31 09:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_add_match_field_to_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.UUIDField(default=uuid.UUID('15ba936b-8556-45e0-a66e-82154ffef72d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
