# Generated by Django 4.1.2 on 2022-10-30 10:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2871f377-6382-41c4-b6c9-acddff076e0f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
