# Generated by Django 4.1.2 on 2022-10-30 10:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_alter_applicant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d9d65f35-676e-4fad-9fcb-40e5cc57c26e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
