# Generated by Django 4.1.2 on 2022-10-30 11:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_create_job_and_application_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b5a23512-c84b-415d-8e8b-7280e426850a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
