# Generated by Django 4.1.2 on 2022-10-30 12:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_alter_applicant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7480639d-77e8-4274-9f22-783d892f3cef'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='portfolio',
            field=models.URLField(null=True),
        ),
    ]
