# Generated by Django 4.1.2 on 2022-10-31 04:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0007_create_applicant_resume_score_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantresumescore',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c0f01624-b9df-4b14-adfa-20101e28e434'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applicantresumescore',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1cba610b-07d3-4245-abb7-0b9c24326aed'), editable=False, primary_key=True, serialize=False),
        ),
    ]
