# Generated by Django 4.1.2 on 2022-10-31 08:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0008_applicantresumescore_applicant_alter_applicant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9e941a46-c208-4a0d-9c29-bd2a95f31950'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applicantresumescore',
            name='id',
            field=models.UUIDField(default=uuid.UUID('68744f72-759a-4d80-ae7d-2d962c90b461'), editable=False, primary_key=True, serialize=False),
        ),
    ]
