# Generated by Django 4.1.2 on 2022-10-31 09:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0009_add_match_field_to_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e2e075c4-4f04-4a56-999a-0d23329c56e3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='social_media',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='applicantresumescore',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ce3ea81a-11ff-47ea-870e-3da7d58942a6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
